[package]
name = "rwcontract"
version = "0.1.0"
authors = ["cezhang52111 <zhangce52111@ruc.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pallet-contracts = { path = "../substrate/frame/contracts" }